#!/bin/sh

cd /tmp

region="br"
# se = sudeste
# br = brasil
# co = centro-oeste
# n	 = norte
# ne = nordeste
# s  = sul

regionFull="BRASIL"
# SUDESTE 		= sudeste
# BRASIL 		= brasil
# CENTRO_OESTE 	= centro-oeste
# NORTE	 		= norte
# NORDESTE 		= nordeste
# SUL  			= sul

infoType="TN"
# TN	= Topo das Nuvens
# VI	= Visivel
# IV 	= Infra-Vermelho termal
# VA	= Vapor d'agua
# VPR	= Vapor d'agua realcado

gifImageSize=30 # dentro do intervalo: [10,30]

URL="http://www.inmet.gov.br/satelites/?produto=GO_${region}_${infoType}&hr=$gifImageSize"
imURL="http://www.inmet.gov.br/projetos/cga/capre/sepra/GEO/GOES12/REGIOES/${regionFull}/"
dopplerFileList="./dopplerFileList"

notify-send "🌦 Baixando imagens de inmet.gov.br, por favor espere!"

curl $URL | grep "Mapa </option>$" | grep -oh "${region}_${infoType}[0-9]*.jpg" > $dopplerFileList  || { notify-send "⛈ Falha ao acessar inmet.gov.br! Tente novamente."; exit; } 

while IFS= read -r line 
do
	wget "${imURL}${line}" || { notify-send "⛈ Falha ao baixar imagens! Tente novamente."; exit; } 
done < "$dopplerFileList"

notify-send "🌤 Download sucedido! Transformando imagens em um GIF..."

convert -delay 30 -loop 0 ${region}_${infoType}*.jpg doppler.gif && notify-send "️☀ Abrindo GIF!" || { notify-send "⛈ Falha na criação do GIF! Tente novamente."; exit; }

rm ./${region}_${infoType}*.jpg
rm $dopplerFileList

mpv --no-osc --loop-file=inf ./doppler.gif

rm ./doppler.gif
